### ISSUE TITLE
[Feature] Add ability to union multiple Google Ads connectors together

### ISSUE THREAD

**Issue by zhyatt** [fivetran/dbt_google_ads_source#34]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I noticed that the Facebook Pages Source dbt package provides an option to union together multiple instances of Facebook Pages connectors for Fivetran: https://hub.getdbt.com/fivetran/facebook_pages_source/latest/. That option isn't available for the Google Ads Source package (https://hub.getdbt.com/fivetran/google_ads_source/latest/), but I am interested in having that included so I can utilize it.

This would likely use the existing `union_data` function in dbt_fivetran_utils package (https://github.com/fivetran/dbt_fivetran_utils/tree/v0.4.2/#union_data-source) similar to how it was done in Facebook Pages.

### Describe alternatives you've considered

We currently work around this limitation with two main changes:

1. We created models to union the source data together and push it to some central views
2. We override the variables that define the source input to this package to change them to use the `ref()` function (a bit hacky), which preserves the ability to have fully integrated scheduling in Fivetran. Here is an example of how the overrides were done in `dbt_project.yml`:
```
  google_ads_source:
    account_history: "{{ ref('stg_google_ads_combined__account_history') }}"
    account_stats: "{{ ref('stg_google_ads_combined__account_stats') }}"
    ad_group_criterion_history: "{{ ref('stg_google_ads_combined__ad_group_criterion_history') }}"
    ad_group_history: "{{ ref('stg_google_ads_combined__ad_group_history') }}"
    ad_group_stats: "{{ ref('stg_google_ads_combined__ad_group_stats') }}"
    ad_history: "{{ ref('stg_google_ads_combined__ad_history') }}"
    ad_stats: "{{ ref('stg_google_ads_combined__ad_stats') }}"
    campaign_history: "{{ ref('stg_google_ads_combined__campaign_history') }}"
    campaign_stats: "{{ ref('stg_google_ads_combined__campaign_stats') }}"
    geo_target: "{{ ref('stg_google_ads_combined__geo_target') }}"
    keyword_stats: "{{ ref('stg_google_ads_combined__keyword_stats') }}"
    label: "{{ ref('stg_google_ads_combined__label') }}"
```

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.
